#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None



class stateVars:
  """
  Attributes:
   - x1
   - x2
   - x3
   - x4
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'x1', None, None, ), # 1
    (2, TType.I32, 'x2', None, None, ), # 2
    (3, TType.I32, 'x3', None, None, ), # 3
    (4, TType.I32, 'x4', None, None, ), # 4
  )

  def __init__(self, x1=None, x2=None, x3=None, x4=None,):
    self.x1 = x1
    self.x2 = x2
    self.x3 = x3
    self.x4 = x4

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.x1 = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.x2 = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.x3 = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I32:
          self.x4 = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('stateVars')
    if self.x1 is not None:
      oprot.writeFieldBegin('x1', TType.I32, 1)
      oprot.writeI32(self.x1)
      oprot.writeFieldEnd()
    if self.x2 is not None:
      oprot.writeFieldBegin('x2', TType.I32, 2)
      oprot.writeI32(self.x2)
      oprot.writeFieldEnd()
    if self.x3 is not None:
      oprot.writeFieldBegin('x3', TType.I32, 3)
      oprot.writeI32(self.x3)
      oprot.writeFieldEnd()
    if self.x4 is not None:
      oprot.writeFieldBegin('x4', TType.I32, 4)
      oprot.writeI32(self.x4)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.x1)
    value = (value * 31) ^ hash(self.x2)
    value = (value * 31) ^ hash(self.x3)
    value = (value * 31) ^ hash(self.x4)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
